set_defaultmode('debug')
add_requires('catch2')

target('shared_ptr_test')
  add_packages('catch2')
  add_files('test/shared_ptr.cpp')
  add_includedirs('include')
  add_cxxflags('-fsanitize=address -fno-omit-frame-pointer')
  add_ldflags('-fsanitize=address -fno-omit-frame-pointer')
  set_warnings('allextra')
  set_languages('cxx20')

target('string_test')
  add_packages('catch2')
  add_files('test/string.cpp')
  add_includedirs('include')
  add_cxxflags('-fsanitize=address -fno-omit-frame-pointer')
  add_ldflags('-fsanitize=address -fno-omit-frame-pointer')
  set_warnings('allextra')
  set_languages('cxx20')

target('any_test')
  add_packages('catch2')
  add_files('test/any.cpp')
  add_includedirs('include')
  add_cxxflags('-fsanitize=address -fno-omit-frame-pointer')
  add_ldflags('-fsanitize=address -fno-omit-frame-pointer')
  set_warnings('allextra')
  set_languages('cxx20')
